name: Golang Code Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:

jobs:
  golangci:
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8
    strategy:
      matrix:
        go-version: [ 1.21.x ]
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - run: |
          go mod tidy
          go mod download

      - uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and
          # must be specified without patch version: we always use the
          # latest patch version.
          version: latest
          skip-pkg-cache: true
          skip-cache: true
          skip-build-cache: true
          args: --timeout 30m -v
        if: env.GIT_DIFF
